{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test_helm.serviceAccountName" . }}
  labels:
{{ include "test_helm.labels" . | nindent 4 }}
{{- end -}}
